POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlBlZWxvIiwiaWQiOiI2MjBhNTY4ZTM3YjgxZGVhMjY0YWFiM2QiLCJpYXQiOjE2NDUxODc5NTZ9.YcjN7CQfpAz-QDXVC8s4IJU3R94OHvls_ur2kkKtiI4

{
	"title": "Pelkoa ja inhoa",
	"author": "S.J. Wee",
	"url": "www.google.com",
	"likes": 4,
	"userId": "620a568e37b81dea264aab3d"
}